language: python
sudo: false

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.9"
  - DJANGO="django==1.8.7"
  - DJANGO="django==1.7.3"
  - DJANGO="django==1.6.3"
  - DJANGO="django==1.5.7"
  - DJANGO="django==1.4.12"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django==1.4.12"
      env: DJANGO="django==1.5.7"
      env: DJANGO="django==1.6.3"
      env: DJANGO="django==1.7.3"

    - python: "3.4"
      env: DJANGO="django==1.4.12"

    - python: "3.3"
      env: DJANGO="django==1.4.12"
      env: DJANGO="django==1.9"

install:
  - pip install $DJANGO
  - pip install django-jinja

script:
  - python runtests.py

notifications:
  email:
    recipients:
      - niwi@niwi.be
    on_success: change
    on_failure: change
